### ISSUE TITLE
Can´t run example - ValueError: zero length field name in format

### ISSUE THREAD

**Issue by frodfigu** [wavexx/facedetect#10]
Hello... I´m trying without success.

I have Python 2.6.6 and I have this error:

`facedetect testCalidad.jpg
Traceback (most recent call last):
  File "/usr/local/bin/facedetect", line 271, in <module>
    sys.exit(__main__())
  File "/usr/local/bin/facedetect", line 265, in __main__
    print("{} {} {} {}".format(*rect))
ValueError: zero length field name in format`

Can you help me? Thank you very much

**Comment by wavexx** [comment]
On Mon, May 30 2016, frodfigu <notifications@github.com> wrote:
> Hello... I´m trying without success.
>
> I have Python 2.6.6 and I have this error:
>
> `facedetect testCalidad.jpg
> Traceback (most recent call last):
>   File "/usr/local/bin/facedetect", line 271, in <module>
>     sys.exit(__main__())
>   File "/usr/local/bin/facedetect", line 265, in __main__
>     print("{} {} {} {}".format(*rect))
> ValueError: zero length field name in format`
>
> Can you help me? Thank you very much

I'm surprised it gets so far with Python 2.6.

The minimal python version I'm testing it is 2.7, and I recommend to
upgrade if possible.

**Comment by frodfigu** [comment]
Thank you for your support.

Solved without update python... 

` print("{0} {0} {0} {0}".format(*rect))`

**Comment by wavexx** [comment]
On Mon, May 30 2016, frodfigu <notifications@github.com> wrote:
> Thank you for your support.
>
> Solved without update python...
>
> ` print("{0} {0} {0} {0}".format(*rect))`

This is incorrect.
It should be:

  print("{0} {1} {2} {3}".format(*rect))

however there are many statements like that in the current source (this
is not the only one).

The main problem is that, as I'm attempting to support python 3 as well,
python 2.7 is really the minimal python is makes sense to support.

I make no guarantees or attempts for any earlier version.

**Comment by frodfigu** [comment]
Thank you... I´ll upgrade my version.

**Comment by wavexx** [comment]
Closing this, as I'll never use 2.6 with opencv 3.x
