### ISSUE TITLE
Installation help for centos?

### ISSUE THREAD

**Issue by agriz** [wavexx/facedetect#11]
Hi

How can i install this in centos?
No package python-opencv available.
No package libopencv-dev available.

**Comment by wavexx** [comment]
I didn't use rh-derivatives in a while. If there's no package already available, OpenCV includes a full tutorial to install python-opencv from source:

http://docs.opencv.org/trunk/dd/dd5/tutorial_py_setup_in_fedora.html

**Comment by wavexx** [comment]
Closing, as no feedback was received (hopefully installed)!
