### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [wavexx/facedetect#13]
Hi,
I have packaged facedetect for Debian.  It would help a lot if you could add release tags since this would easily enable detecting new versions and always provide the latest release state.
Kind regards and thanks for providing facedetext ad free software, Andreas.

**Comment by wavexx** [comment]
I really have no development "agenda" on it though, which is why I still didn't explicitly make tags. Given how slow development is, you might still want to check for actual fresher commits...

If you're fine with that, I'm accepting suggestions on which version number the first release should be ;)

**Comment by tillea** [comment]
Hi,

On Thu, Dec 08, 2016 at 09:57:11AM -0800, wavexx wrote:
> I really have no development "agenda" on it though, which is why I still didn't explicitly make tags. Given how slow development is, you might still want to check for actual fresher commits...

The thing is that our tools are not able to detect new commits and
commit ids do not provide any sequence in terms of a sorting order.
 
> If you're fine with that, I'm accepting suggestions on which version number the first release should be ;)

If you would like to start with 0.1 now and have say some bugfix commit
with no new feature I'd suggest 0.1.1.  In case of a new feature (in
terms of command line option or output) or in terms of a new quality in
detecting images you could bump to 0.2.  BTW, I'm about to file issues
for not correctly detected images soon (but probably not before
Christmas).  If you want a preview what I mean here are two examples:

    http://fam-tille.de/vietnam/2016/#111
    http://fam-tille.de/vietnam/2016/#327

I think a version 0.2 might be a feature to even detect these "faces"

    http://fam-tille.de/vietnam/2016/#297

... but honestly I do not really expect this. ;-)

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by wavexx** [comment]
v0.1 tagged with the current master
