### ISSUE TITLE
Facedetect fails on Fedora system

### ISSUE THREAD

**Issue by oujesky** [wavexx/facedetect#14]
When running facedetect script on Fedora system (and possibly other rpm based distributions), it fails with the following error:

```facedetect: error: cannot load HAAR_FRONTALFACE_ALT2 from /usr/share/opencv/haarcascades/haarcascade_frontalface_alt2.xml```

This is caused due to fact that OpenCV package on Fedora has its data installed to `/usr/share/OpenCV` instead of `/usr/share/opencv`.

**Comment by wavexx** [comment]
On Sun, Dec 11 2016, Miroslav Oujeský wrote:
> This is caused due to fact that OpenCV package on Fedora has its data
> installed to `/usr/share/OpenCV` instead of `/usr/share/opencv`.

Every distribution has it's own data path for opencv. The best option
would be for the package in fedora to patch it's own location.

Alternatively there's now also the `--data-dir` flag to change the
location of the data directory at runtime.
