### ISSUE TITLE
Error with basic functions

### ISSUE THREAD

**Issue by darksipu** [wavexx/facedetect#16]
Hi there, 

I'm running this on Python3, OpenCV3 on an iMac and I'm running into this problem when trying to use the basic functions:

(cv) woland:facedetect dcr$ ./facedetect -o /Users/dcr/Desktop/p113.jpg
usage: facedetect [-h] [--biggest] [--best] [-c] [--data-dir DIRECTORY] [-q]
                  [-s FILE] [--search-threshold PERCENT] [-o OUTPUT] [-d]
                  file
facedetect: error: the following arguments are required: file

Any ideas?

Thanks, 
Florin

**Comment by wavexx** [comment]
On Fri, Feb 03 2017, darksipu wrote:
> (cv) woland:facedetect dcr$ ./facedetect -o /Users/dcr/Desktop/p113.jpg
> usage: facedetect [-h] [--biggest] [--best] [-c] [--data-dir DIRECTORY] [-q]
>                   [-s FILE] [--search-threshold PERCENT] [-o OUTPUT] [-d]
>                   file
> facedetect: error: the following arguments are required: file

You shouldn't use -o in this case. Just:

  facedetect [file]

If you want debugging, -o specifies an _output_ file:

  facedetect -o debug-of-image.jpg image.jpg
