### ISSUE TITLE
[Question] How to load from STDIN?

### ISSUE THREAD

**Issue by TamasBarta** [wavexx/facedetect#17]
Hi,

I couldn't manage to make facedetect use the STDIN as a source. Is it possible at all?

Thanks!

**Comment by wavexx** [comment]
On Wed, Feb 22 2017, Tamás Barta wrote:
> Hi,
>
> I couldn't manage to make facedetect use the STDIN as a source. Is it possible at all?

It's not currently possible, but it not hard to modify the script to do
so.
