### ISSUE TITLE
camera support?

### ISSUE THREAD

**Issue by albertyou2** [wavexx/facedetect#18]
hi @wavexx 
very interesting work! 
is there any video version ? I mean could i use this face detector detect faces and crop them  automaticly with image stream from a camera？
thank you!

**Comment by wavexx** [comment]
On Sat, Feb 25 2017, albertyou2 wrote:
> is there any video version ? I mean could i use this face detector
> detect faces and crop them automaticly with image stream from a camera？

No, there is no video support.

**Comment by albertyou2** [comment]
i see 
thank you
