### ISSUE TITLE
NEWBIE import numpy as np error

### ISSUE THREAD

**Issue by BLCKPSTV** [wavexx/facedetect#19]
Hey new at this and probably more an issue from my side.

I get following error when running ./facedetect doc/persons.jpg in anaconda environment. 

```
`~/Documents/facedetect$ ./facedetect doc/person.jpg
Traceback (most recent call last):
  File "./facedetect", line 8, in <module>
    import numpy as np
ImportError: No module named 'numpy'
`
```

Numpy is installed in global anaconda directory

Any help would be useful, really keen on getting this to work on my images

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, BLCKPSTV wrote:
> ```
> `~/Documents/facedetect$ ./facedetect doc/person.jpg
> Traceback (most recent call last):
>   File "./facedetect", line 8, in <module>
>     import numpy as np
> ImportError: No module named 'numpy'
> `
> ```
>
> Numpy is installed in global anaconda directory

Then probably the incorrect python version is used.
Make it explicit:

$ python3 ./facedetect doc/person.jpg

**Comment by BLCKPSTV** [comment]
Hey indeed, I'd installed a python 2.7 environment.
I did install a new env with 3.6 but got the same error. Below the steps I did to run on anaconda. 

```
~/Documents/facedetect$ conda create -n facedetect python=3.6
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/Imac/anaconda2/envs/facedetect:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0     
    certifi:         2017.7.27.1-py36h8b7b77e_0
    libedit:         3.1-heed3624_0            
    libffi:          3.2.1-h4deb6c0_3          
    libgcc-ng:       7.2.0-h7cc24e2_2          
    libstdcxx-ng:    7.2.0-h7a57d05_2          
    ncurses:         6.0-h06874d7_1            
    openssl:         1.0.2l-h077ae2c_5         
    pip:             9.0.1-py36h8ec8b28_3      
    python:          3.6.3-hc9025b9_1          
    readline:        7.0-hac23ff0_3            
    setuptools:      36.5.0-py36he42e2e1_0     
    sqlite:          3.20.1-h6d8b0f3_1         
    tk:              8.6.7-h5979e9b_1          
    wheel:           0.29.0-py36he7f4e38_1     
    xz:              5.2.3-h2bcbf08_1          
    zlib:            1.2.11-hfbfcf68_1         

Proceed ([y]/n)? y

python-3.6.3-h 100% |################################| Time: 0:00:03   9.25 MB/s
certifi-2017.7 100% |################################| Time: 0:00:00  11.23 MB/s
setuptools-36. 100% |################################| Time: 0:00:00  11.85 MB/s
wheel-0.29.0-p 100% |################################| Time: 0:00:00   3.51 MB/s
pip-9.0.1-py36 100% |################################| Time: 0:00:00  11.54 MB/s
#
# To activate this environment, use:
# > source activate facedetect
#
# To deactivate an active environment, use:
# > source deactivate
#

iMac:~/Documents/facedetect$ conda install -n facedetect numpy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/quinten/anaconda2/envs/facedetect:

The following NEW packages will be INSTALLED:

    intel-openmp: 2018.0.0-h15fc484_7  
    mkl:          2018.0.0-hb491cac_4  
    numpy:        1.13.3-py36ha12f23b_0

Proceed ([y]/n)? y

numpy-1.13.3-p 100% |################################| Time: 0:00:00   9.28 MB/s
iMac:~/Documents/facedetect$ ls
COPYING.txt  doc  facedetect  README.rst  sys
iMac:~/Documents/facedetect$ python3 ./facedetect doc/person.jpgTraceback (most recent call last):
  File "./facedetect", line 8, in <module>
    import numpy as np
ImportError: No module named 'numpy'

```

Small note, this is on Ubuntu (REFIND on a Imac)

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, BLCKPSTV wrote:
> iMac:~/Documents/facedetect$ python3 ./facedetect doc/person.jpgTraceback (most recent call last):
>   File "./facedetect", line 8, in <module>
>     import numpy as np
> ImportError: No module named 'numpy'

Try running ``python3 --version`` and ``python --version``.
The anaconda version should clearly be visible.

**Comment by BLCKPSTV** [comment]
Oops that's my bad! 
I didn't activate my environment!! :-1: 

I got following error: 

```
python3 ./facedetect doc/person.jpg
facedetect: error: cannot load HAAR_FRONTALFACE_ALT2 from /usr/share/opencv/haarcascades/haarcascade_frontalface_
```

I guess this is a library or something missing? I'll find a solution. 

Thanks for clearing up the simple misunderstanding from python3 :+1:

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, BLCKPSTV wrote:
> python3 ./facedetect doc/person.jpg
> facedetect: error: cannot load HAAR_FRONTALFACE_ALT2 from /usr/share/opencv/haarcascades/haarcascade_frontalface_
>
> I guess this is a library or something missing? I'll find a solution.

This is a file contained in opencv-data or libopencv-dev (depending on
the ubuntu version).

It's the trained model for face recognition.

**Comment by BLCKPSTV** [comment]
Should I download these files or are they connected with conda install opencv (which I did already, so my guess here is no. And I need to manually link and get those files.) 
I'm running ubuntu 16.04. 

When searching for haarcascades in opencv-data I get this github page [here](https://github.com/opencv/opencv/tree/master/data/haarcascades)

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, BLCKPSTV wrote:
> Should I download these files or are they connected with conda install
> opencv (which I did already, so my guess here is no. And I need to
> manually link and get those files.) I'm running ubuntu 16.04.

conda probably installs those files, but in a different location. Try to
make a system-wide search using "locate".

You can then point facedetect to the directory containing the files
using the "--data-dir" flag. data-dir is normally /usr/share/opencv and
it's the directory containing "haarcascades".

You can also download them from github.

**Comment by BLCKPSTV** [comment]
Awesome! 
I found the opencv directory and changed the dir in the facedetect.py to my location and got the corresponding data back like this! 

```
/Documents/facedetect$ python3 ./facedetect doc/person.jpg
320 32 196 196
75 304 229 229
395 317 237 237

```
![person](https://user-images.githubusercontent.com/6031569/32022438-b125ceae-b9d6-11e7-9a72-3ab4c66208ae.jpg)

from this picture, So if i'm correct in sees 3 faces? 

Anyways I can test and tryout now!! Thanks so much!!

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, BLCKPSTV wrote:
> /Documents/facedetect$ python3 ./facedetect doc/person.jpg
> 320 32 196 196
> 75 304 229 229
> 395 317 237 237
>
> ```
> ![person](https://user-images.githubusercontent.com/6031569/32022438-b125ceae-b9d6-11e7-9a72-3ab4c66208ae.jpg)
>
> from this picture, So if i'm correct in sees 3 faces?

Try ``python3 -d -o test.jpg ./facedetect doc/person.jpg`` and look at
test.jpg to see where the faces are.

**Comment by BLCKPSTV** [comment]
I'm getting this 

```
Unknown option: -o
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

```

I'm also trying to make separated pictures of the faces, but still having trouble installing .imagemagick and then figuring out how to convert these. All new to me, sorry for any hassle! :)

**Comment by BLCKPSTV** [comment]
Hmm, I still didn't find (google) what the -o is and why I can't use it ... :/

**Comment by wavexx** [comment]
On Wed, Oct 25 2017, Yuri D'Elia wrote:
> Try ``python3 -d -o test.jpg ./facedetect doc/person.jpg`` and look at
> test.jpg to see where the faces are.

I should have written:

  python3 ./facedetect -d -o test.jpg  doc/person.jpg

sorry.

**Comment by BLCKPSTV** [comment]
Awesome!! It works, silly of me that I not see that those should be after I launch the script and not before!

Thank you so much!!

**Comment by BLCKPSTV** [comment]
Very last question (promise ^^) (also maybe I should start a new issue for this for people in the future maybe?) 

But how do I run this: 

```
for file in path/to/pictures/*.jpg; do
  name=$(basename "$file")
  i=0
  facedetect "$file" | while read x y w h; do
    convert "$file" -crop ${w}x${h}+${x}+${y} "path/to/faces/${name%.*}_${i}.${name##*.}"
    i=$(($i+1))
  done
done
```

is this in the terminal? 

Because when I run this witht python3 ./facedetect and then the code.
I get` facedetect: command not found`

When I run this in python in my virtual env. I get more errors. 

```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> for file in d/*.jpg; do
  File "<stdin>", line 1
    for file in d/*.jpg; do
                  ^
SyntaxError: invalid syntax
>>>   name=$(basename "$file")
  File "<stdin>", line 1
    name=$(basename "$file")
    ^
IndentationError: unexpected indent
>>>   i=0
  File "<stdin>", line 1
    i=0
    ^
IndentationError: unexpected indent
>>>   facedetect "$file" | while read x y w h; do
  File "<stdin>", line 1
    facedetect "$file" | while read x y w h; do
    ^
IndentationError: unexpected indent
>>>     convert "$file" -crop ${w}x${h}+${x}+${y} "path/to/faces/${name%.*}_${i}.${name##*.}"
  File "<stdin>", line 1
    convert "$file" -crop ${w}x${h}+${x}+${y} "path/to/faces/${name%.*}_${i}.${name##*.}"
    ^
IndentationError: unexpected indent
>>>     i=$(($i+1))
  File "<stdin>", line 1
    i=$(($i+1))
    ^
IndentationError: unexpected indent
>>>   done
  File "<stdin>", line 1
    done
    ^
IndentationError: unexpected indent
>>> don
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'don' is not defined
>>> exit()

```

I've install image magick via sudo apt get. 
I've looked up the convert usage, but that states nothing on how to use it in terminal or command line and or how I can combine that with an existing script.

**Comment by wavexx** [comment]
On Thu, Oct 26 2017, BLCKPSTV wrote:
> is this in the terminal?

This is a shell script, but it's only a template: it needs to be
customized. Notice how "path/to/pictures" and "path/to/faces" are only
placeholders for real directories.

Similarly you can change "facedetect" to "python3 facedetect ...".

> Because when I run this witht python3 ./facedetect and then the code.
> I get` facedetect: command not found`

Normally you would install facedetect to a standard directory, so that
you don't need to use ./ at all. Now that you activated your python
environment properly, using python3 explicitly should also not be
needed.

Note that unless you explicitly need conda, "facedetect" is also
available in the universe section of ubuntu zesty, which would install
facedetect properly with just "apt-get install facedetect".

**Comment by BLCKPSTV** [comment]
Ok, 

I did following

```
python facedect
for file in doc/*.jpg; do  // existing doc
  name=$(basename "$file")
  i=0
  facedetect "$file" | while read x y w h; do
    convert "$file" -crop ${w}x${h}+${x}+${y} "doc2/${name%.*}_${i}.${name##*.}" //also existing doc
    i=$(($i+1))
  done
done
```
Error:
```
facedetect: command not found
facedetect: command not found
```

Then I tought I will install your apt-get way in the virtual env. 
Which gives me this error. 

```
apt-get install facedetect
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```
then with sudo

```
sudo apt-get install facedetect
[sudo] password for quinten: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package facedetect
```
Though I am not running Zesty I'm running 16.04.

**Comment by BLCKPSTV** [comment]
Is it possible to make this for 16.04 or tell me how to locate the package, I've read to every error on google and nothing makes me wiser in finding the solution. 
Your facedetect script is the one thing I got so far in to working (except for the convert shell script)

**Comment by wavexx** [comment]
On Fri, Oct 27 2017, BLCKPSTV wrote:
> python facedect
> for file in doc/*.jpg; do  // existing doc
>   name=$(basename "$file")
>   i=0
>   facedetect "$file" | while read x y w h; do
    ^^^^^^^^^^

This should be changed to "python3 facedetect", just like you normally
call facedetect.

> Error:
> ```
> facedetect: command not found
> facedetect: command not found
> ```

Another approach is to install facedetect to a standard location:

  sudo cp facedetect /usr/local/bin

You should have a look to a basic unix/scripting tutorial to have an
idea of how this works in a general sense.

> Though I am not running Zesty I'm running 16.04.

It's currently available only since Zesty:

  https://packages.ubuntu.com/search?keywords=facedetect&searchon=names

**Comment by BLCKPSTV** [comment]
Hi, thanks for all the patience.

I've reinstalled to zesty, global install and now it's working!! 

Needed to install imagemagick latest as well. But now everything works!! 

More question than an issue, is there a way to make each crop the same size ex. 128x128 crops?

Kindest regards and :+1: for all your work on this!!

**Comment by BLCKPSTV** [comment]
Also how do I batch convert pictures? 

```
python facedetect
for file in /home/quinten/Atthedoctor/****.jpeg; do    = what do I call the image to read all images in that folder?
  name=$(basename "$file")
  i=0
  facedetect "$file" | while read x y w h; do
    convert "$file" -crop ${w}x${h}+${x}+${y} "doc2/${name%.*}_${i}.${name##*.}"
    i=$(($i+1))
  done
done
```

**Comment by wavexx** [comment]
On Tue, Oct 31 2017, BLCKPSTV wrote:
> Hi, thanks for all the patience.
>
> I've reinstalled to zesty, global install and now it's working!!
>
> Needed to install imagemagick latest as well. But now everything works!!
>
> More question than an issue, is there a way to make each crop the same
> size ex. 128x128 crops?

You should *really* read some documentation about scripting and the
documentation about imagemagick itself. This is way beyond what
facedetect does.

convert [flags] -size '128x128>' [output] will rescale the faces down to
128x128 (at most). However the order of the parameter is important in
all imagemagick tools.

See https://www.imagemagick.org/Usage/resize/#shrink
