### ISSUE TITLE
How to use the --best in the for loop

### ISSUE THREAD

**Issue by BLCKPSTV** [wavexx/facedetect#20]
Hi, 

quick question?
How do I make the --best flag work in the for loop example to extract the faces to seperate jpg files?

It's only explained in the command line example.

**Comment by wavexx** [comment]
On Sun, Dec 03 2017, BLCKPSTV wrote:
> Hi,
>
> quick question?
> How do I make the --best flag work in the for loop example to extract the faces to
> seperate jpg files?

Best doesn't change the output format of facedetect, so simply add
--best to the command.

**Comment by BLCKPSTV** [comment]
--best does give the best detection of a face, doesn't it? 

So If I put it in the code (below) which I run directly from the terminal, do I do at as such 

```
python facedetect  #--best here? because this gives an error.
for file in /home/myname/Documents/facedetect/download1/*.jpg; do
>   name=$(basename "$file")
>   i=0
>   facedetect "$file" | while read x y w h; do
>     convert "$file" -crop ${w}x${h}+${x}+${y} "/home/quinten/Documents/facedetect/download1faces/${name%.*}_${i}.${name##*.}"
>     i=$(($i+1))
>   done
> done

```

**Comment by wavexx** [comment]
````shell
for file in /home/myname/Documents/facedetect/download1/*.jpg; do
  name=$(basename "$file")
  i=0
  python facedetect --best "$file" | while read x y w h; do
    convert "$file" -crop "${w}x${h}+${x}+${y}" "/home/quinten/Documents/facedetect/download1faces/${name%.*}_${i}.${name##*.}"
    i=$(($i+1))
  done
done
````

**Comment by BLCKPSTV** [comment]
Thanks!!
As I thought I should have looked longer on it to find it. My focus was pretty off! For it is super...

Yet again thanks!!!
